#!/usr/bin/env ruby
# Compare the 302 alphabetical index entries against existing YAML concept files.

# Mapping: concept_number => [term1, term2, ...]
INDEX = {
  "2.2.3" => ["Admission à la vérification"],
  "1.2" => ["Agents de vérification"],
  "2.8.1" => ["Ajuster"],
  "6.1.2" => ["Appareil mesureur", "Appareil mesureur à lecture directe", "Appareil mesureur de comparaison", "Appareil mesureur différentiel"],
  "6.1.2.6" => ["Appareil mesureur conditionneur"],
  "6.1.2.7" => ["Appareil mesureur enregistreur"],
  "6.1.2.1" => ["Appareil mesureur indicateur"],
  "6.1.2.2" => ["Appareil mesureur intégrateur"],
  "6.1.2.5" => ["Appareil mesureur prédéterminateur"],
  "6.1.2.4" => ["Appareil mesureur totalisateur"],
  "2.2.1" => ["Approbation d'un modèle"],
  "2.2.2" => ["Approbation d'un modèle à titre provisoire"],
  "1.3" => ["Autorités de surveillance métrologique"],
  "7.4.4.1" => ["Base d'une échelle à traits"],
  "1.1.6" => ["Bureau de vérification ambulant"],
  "1.1.5" => ["Bureau local de vérification"],
  "1.1.1" => ["Bureau national de métrologie légale"],
  "1.1.3" => ["Bureau national de vérification"],
  "1.1.4" => ["Bureau régional de vérification"],
  "9.2.8" => ["Cadence de mesurage maximale", "Cadence de mesurage minimale"],
  "7.5" => ["Cadran", "Limbe", "Tambour gradué"],
  "2.8.2" => ["Calibrer"],
  "7.3.1" => ["Capteur"],
  "7.1" => ["Catégorie d'instruments de mesurage"],
  "1.1.7" => ["Centre de vérification"],
  "3.3.2" => ["Certificat d'étalonnage", "Certificat d'expertise"],
  "3.3.1" => ["Certificat de vérification"],
  "7.3" => ["Chaîne de mesurage"],
  "9.2.3" => ["Charge d'un compteur"],
  "9.2.5" => ["Charge maximale d'un compteur"],
  "9.2.6" => ["Charge minimale d'un compteur"],
  "7.4.1" => ["Chiffraison d'une échelle"],
  "9.10.4" => ["Classe de précision"],
  "8.2.6.2.1" => ["Coefficient de température d'un instrument de mesurage"],
  "6.1.2.3" => ["Compteur"],
  "9.1.3" => ["Conditions de référence"],
  "9.1" => ["Conditions usuelles d'emploi"],
  "5.3.1" => ["Constante d'un instrument de mesurage"],
  "2.1" => ["Contrôle des instruments de mesurage"],
  "8.1.1.1" => ["Correction"],
  "9.5.3" => ["Correction de justesse"],
  "8.6.1" => ["Courbe d'étalonnage d'un instrument de mesurage"],
  "8.6.2" => ["Courbe de correction d'un instrument de mesurage"],
  "8.6" => ["Courbe d'erreurs d'un instrument de mesurage"],
  "7.8" => ["Cycle de fonctionnement d'un appareil mesureur"],
  "4.3.3" => ["Dimension d'une grandeur"],
  "9.6.1" => ["Dispersion des indications"],
  "6.2" => ["Dispositif auxiliaire de mesurage"],
  "7.3.3" => ["Dispositif indicateur"],
  "9.1.2" => ["Domaine de référence"],
  "9.1.4" => ["Domaine nominal d'utilisation"],
  "8.1.7.2" => ["Écart moyen quadratique de la moyenne arithmétique d'une série de mesurages"],
  "8.2.4" => ["Écart moyen quadratique d'une seule indication dans une série d'indications"],
  "8.1.7.1" => ["Écart moyen quadratique d'un seul mesurage dans une série de mesurages"],
  "7.4" => ["Échelle"],
  "7.4.4" => ["Échelle à traits"],
  "7.4.4.2.2" => ["Échelle à valeur d'échelon constante"],
  "4.5" => ["Échelle de repérage d'une grandeur"],
  "7.4.4.2.1" => ["Échelle équidistante"],
  "7.4.4.2.3" => ["Échelle linéaire"],
  "7.4.5.2" => ["Échelle non-linéaire"],
  "7.4.5" => ["Échelle numérique"],
  "7.4.4.2.4" => ["Échelle régulière"],
  "7.4.5.1" => ["Échelle semi-numérique"],
  "7.4.3" => ["Échelon"],
  "7.3.1.1" => ["Élément récepteur du capteur"],
  "7.3.2" => ["Élément transducteur d'un appareil mesureur"],
  "7.4.4.2" => ["Équation d'une échelle à traits"],
  "4.4" => ["Équation entre grandeurs"],
  "4.4.2" => ["Équation entre unités de mesure"],
  "4.4.1" => ["Équation entre valeurs numériques"],
  "6.3.1" => ["Équipement de mesurage"],
  "8.1.5" => ["Erreur absolue"],
  "8.1.5.3" => ["Erreur absolue apparente"],
  "8.1.5.1" => ["Erreur absolue véritable"],
  "8.2.6.1" => ["Erreur complémentaire d'un instrument de mesurage"],
  "8.2.6" => ["Erreur de base d'un instrument de mesurage"],
  "8.2.5" => ["Erreur de calibrage d'une mesure matérialisée"],
  "9.6.3" => ["Erreur de fidélité"],
  "9.5.1" => ["Erreur de justesse"],
  "8.5.1" => ["Erreur de lecture"],
  "8.1" => ["Erreur de mesurage"],
  "8.4" => ["Erreur de méthode"],
  "9.8.1" => ["Erreur de mobilité"],
  "8.5.1.1" => ["Erreur de parallaxe"],
  "9.10.1" => ["Erreur de précision"],
  "9.7.1" => ["Erreur de réversibilité"],
  "8.2.3" => ["Erreur de zéro"],
  "8.2.1" => ["Erreur d'une mesure matérialisée"],
  "8.2.2" => ["Erreur d'un appareil mesureur"],
  "8.5.1.2" => ["Erreur d'interpolation"],
  "8.5" => ["Erreur d'observation"],
  "8.2.6.2" => ["Erreur due à la température"],
  "8.2.6.4" => ["Erreur due à l'inertie"],
  "8.2.6.3" => ["Erreur due au frottement"],
  "8.1.2" => ["Erreur fortuite"],
  "8.2" => ["Erreur instrumentale"],
  "9.6.4" => ["Erreurs limites de fidélité"],
  "8.1.8.2" => ["Erreurs limites de la moyenne arithmétique d'une série de mesurages"],
  "9.8.2" => ["Erreur limite de mobilité"],
  "9.10.2" => ["Erreurs limites de précision"],
  "9.7.2" => ["Erreur limite de réversibilité"],
  "8.1.8.1" => ["Erreurs limites d'un seul mesurage d'une série"],
  "9.6.5" => ["Erreurs maximales tolérées de fidélité"],
  "9.5.2" => ["Erreurs maximales tolérées de justesse"],
  "9.10.3" => ["Erreurs maximales tolérées de précision"],
  "9.7.3" => ["Erreur maximale tolérée de réversibilité"],
  "8.3.1" => ["Erreurs maximales tolérées en service"],
  "8.3" => ["Erreurs maximales tolérées lors de la vérification"],
  "8.1.3" => ["Erreur parasite"],
  "8.1.4.1" => ["Erreur partielle"],
  "8.1.6" => ["Erreur relative"],
  "8.1.1" => ["Erreur systématique"],
  "2.2" => ["Essai d'un modèle"],
  "6.4" => ["Étalon"],
  "6.4.3" => ["Étalon collectif"],
  "6.4.7" => ["Étalon de référence"],
  "6.4.8" => ["Étalon de travail"],
  "6.4.2" => ["Étalon individuel"],
  "6.4.9" => ["Étalon international"],
  "6.4.10" => ["Étalon national"],
  "6.4.4" => ["Étalon primaire"],
  "6.4.6" => ["Étalon secondaire"],
  "6.4.5" => ["Étalon-témoin"],
  "2.5" => ["Étalonnage"],
  "9.6.2" => ["Étendue de dispersion des indications"],
  "9.2.4" => ["Étendue de la charge d'un compteur"],
  "7.4.2.1" => ["Étendue de l'échelle"],
  "9.2" => ["Étendue de mesurage"],
  "2.3.3" => ["Examen administratif externe"],
  "2.3.1" => ["Examen de conformité avec le modèle approuvé"],
  "2.3.5" => ["Examen de surveillance"],
  "2.3" => ["Examen d'un instrument de mesurage"],
  "2.3.4" => ["Examen métrologique"],
  "2.3.2" => ["Examen préalable"],
  "7.1.2.3" => ["Exemplaire témoin d'un modèle approuvé"],
  "2.5.1" => ["Expertise métrologique"],
  "9.5.4" => ["Facteur de correction de justesse"],
  "9.6" => ["Fidélité d'un instrument de mesurage"],
  "2.8.3" => ["Graduer"],
  "4.1.1" => ["Grandeur à mesurer"],
  "4.3.1" => ["Grandeur de base"],
  "4.3.2" => ["Grandeur dérivée"],
  "4.1.2" => ["Grandeur d'influence"],
  "4.1" => ["Grandeur mesurable"],
  "4.3.4" => ["Grandeur sans dimension"],
  "8.1.9" => ["Imprécision de mesurage"],
  "8.1.8.4" => ["Incertitude de la moyenne arithmétique d'une série"],
  "8.1.8" => ["Incertitude de mesurage"],
  "8.1.8.3" => ["Incertitude d'un seul mesurage d'une série"],
  "7.3.3.1" => ["Index"],
  "5.3" => ["Indication d'un instrument de mesurage"],
  "3.4" => ["Inscriptions d'identification d'un instrument de mesurage"],
  "6.3" => ["Installation de mesurage"],
  "1.1.2" => ["Institut national de métrologie légale"],
  "3.1.4" => ["Instruction relative à la vérification"],
  "6.1" => ["Instruments de mesurage"],
  "6.1.4" => ["Instrument de mesurage admissible à la vérification"],
  "6.1.6" => ["Instrument de mesurage auxiliaire"],
  "6.1.5" => ["Instrument de mesurage légal"],
  "6.1.3" => ["Instrument de mesurage usuel"],
  "9.5" => ["Justesse d'un instrument de mesurage"],
  "8.1.4" => ["Loi de composition des erreurs"],
  "3.1" => ["Loi relative à la métrologie légale"],
  "7.4.3.1" => ["Longueur de l'échelon"],
  "3.2.4" => ["Marque annuelle"],
  "3.2.7" => ["Marque d'approbation de modèle"],
  "3.2.5" => ["Marque de refus"],
  "3.2.1" => ["Marque de vérification"],
  "3.2.3" => ["Marque du bureau"],
  "3.2" => ["Marques d'un instrument de mesurage"],
  "3.2.2" => ["Marque principale de vérification"],
  "3.2.6" => ["Marques de protection"],
  "5.1" => ["Mesurage"],
  "6.1.1" => ["Mesure matérialisée", "Mesure matérialisée autosuffisante", "Mesure matérialisée non-autosuffisante"],
  "5.2" => ["Méthode de mesurage"],
  "5.2.3" => ["Méthode de mesurage combinatoire en séries fermées"],
  "5.2.5.2" => ["Méthode de mesurage différentiel"],
  "5.2.1" => ["Méthode de mesurage direct"],
  "5.2.4" => ["Méthode de mesurage fondamental"],
  "5.2.2" => ["Méthode de mesurage indirect"],
  "5.2.5.2.1" => ["Méthode de mesurage par coïncidence"],
  "5.2.5" => ["Méthode de mesurage par comparaison"],
  "5.2.5.1" => ["Méthode de mesurage par comparaison directe"],
  "5.2.5.3" => ["Méthode de mesurage par déviation"],
  "5.2.5.1.1" => ["Méthode de mesurage par substitution"],
  "5.2.5.1.2" => ["Méthode de mesurage par transposition"],
  "6.4.1" => ["Méthode étalon"],
  "0.1" => ["Métrologie"],
  "0.3" => ["Métrologie appliquée"],
  "0.2" => ["Métrologie générale"],
  "0.6" => ["Métrologie légale"],
  "0.3.1" => ["Métrologie technique"],
  "0.4" => ["Métrologie théorique"],
  "9.8" => ["Mobilité d'un instrument de mesurage"],
  "7.1.2.2" => ["Modèle approuvé"],
  "7.1.2.1" => ["Modèle d'un instrument de mesurage"],
  "7.1.2" => ["Modèle provisoire d'un instrument de mesurage"],
  "5.4.4" => ["Moyenne pondérée"],
  "2.7.1" => ["Oblitération de la marque de vérification"],
  "5.3.2" => ["Observation de l'indication"],
  "2.4.11" => ["Perte de validité de la vérification"],
  "5.4.3" => ["Poids d'un mesurage"],
  "3.3" => ["Poinçon"],
  "2.7" => ["Poinçonnage"],
  "9.2.1" => ["Portée maximale"],
  "9.2.2" => ["Portée minimale"],
  "9.10" => ["Précision d'un instrument de mesurage"],
  "3.1.2" => ["Prescriptions relatives à l'approbation des modèles"],
  "3.1.1" => ["Prescriptions relatives à la vérification d'instruments de mesurage assujettis / dispensés"],
  "2.4.9" => ["Présentation à la vérification / à l'étalonnage"],
  "5.1.1" => ["Principe de mesurage"],
  "5.1.2" => ["Processus de mesurage"],
  "6.4.11" => ["Prototype international / national"],
  "2.4.10" => ["Refus d'un instrument de mesurage"],
  "7.3.3.2" => ["Repère"],
  "5.5" => ["Répétabilité des mesurages"],
  "5.5.1" => ["Reproductibilité des mesurages"],
  "5.4.1" => ["Résultat brut d'un mesurage"],
  "5.4.2" => ["Résultat corrigé d'un mesurage"],
  "5.4" => ["Résultat d'un mesurage"],
  "9.7" => ["Réversibilité d'un instrument de mesurage"],
  "7.2.1" => ["Schéma de principe"],
  "7.2" => ["Schéma de structure"],
  "6.5" => ["Schéma d'une hiérarchie des instruments de mesurage"],
  "9.4" => ["Sensibilité d'un instrument de mesurage"],
  "1.1" => ["Service national de métrologie légale"],
  "9.8.4" => ["Seuil de démarrage d'un compteur"],
  "9.8.3" => ["Seuil de mobilité"],
  "3.1.3" => ["Spécification des instruments de mesurage assujettis à la vérification"],
  "7.6" => ["Support d'enregistrement"],
  "9.2.7" => ["Surcharge d'un instrument de mesurage"],
  "9.3" => ["Sûreté de lecture d'un instrument de mesurage"],
  "2.6" => ["Surveillance métrologique"],
  "4.6.1" => ["Symbole de l'unité de mesure"],
  "4.7.1" => ["Système cohérent d'unités de mesure"],
  "4.3" => ["Système de grandeurs"],
  "7.1.1" => ["Système d'un instrument de mesurage"],
  "4.7" => ["Système d'unités de mesure"],
  "4.7.3" => ["Système International d'Unités (SI)"],
  "4.7.2" => ["Système métrique décimal"],
  "0.5" => ["Technique des mesurages"],
  "9.9" => ["Temps de réponse d'un instrument de mesurage"],
  "7.7" => ["Totalisateur"],
  "6.1.7" => ["Transducteur de mesurage"],
  "4.6" => ["Unité de mesure"],
  "4.6.5" => ["Unité de mesure cohérente"],
  "4.6.3" => ["Unité de mesure de base"],
  "4.6.4" => ["Unité de mesure dérivée"],
  "4.6.6" => ["Unité de mesure hors-système"],
  "4.6.2" => ["Unité de mesure légale"],
  "4.6.7" => ["Unité de mesure multiple / sous-multiple"],
  "8.1.5.2" => ["Valeur absolue de l'erreur"],
  "4.2.1.1" => ["Valeur conventionnellement vraie d'une grandeur"],
  "5.3.5" => ["Valeur conventionnellement vraie d'une mesure matérialisée"],
  "7.4.3.2" => ["Valeur de l'échelon"],
  "9.1.1" => ["Valeur de référence"],
  "4.2" => ["Valeur d'une grandeur déterminée"],
  "7.4.2.1.2" => ["Valeur maximale de l'échelle"],
  "7.4.2.1.1" => ["Valeur minimale de l'échelle"],
  "5.3.4" => ["Valeur nominale partielle d'une mesure matérialisée"],
  "5.3.3" => ["Valeur nominale totale d'une mesure matérialisée"],
  "4.2.2" => ["Valeur numérique d'une grandeur"],
  "4.2.1" => ["Valeur vraie d'une grandeur"],
  "8.2.6.1.1" => ["Variation d'indication d'un instrument de mesurage"],
  "2.4" => ["Vérification"],
  "2.4.4" => ["Vérification complète"],
  "2.4.7" => ["Vérification exceptionnelle"],
  "2.4.8" => ["Vérification obligatoire"],
  "2.4.1" => ["Vérification par échantillonnage"],
  "2.4.6" => ["Vérification périodique"],
  "2.4.2" => ["Vérification primitive"],
  "2.4.5" => ["Vérification simplifiée"],
  "2.4.3" => ["Vérification ultérieure"],
  "7.4.2" => ["Zone de l'échelle"],
  "8.1.8.5" => ["Zone d'incertitude de mesurage"],
}

yaml_ids = Dir.glob("datasets/viml-1968/concepts/*.yaml").map { |f| File.basename(f, ".yaml") }.to_set

missing = INDEX.keys.reject { |k| yaml_ids.include?(k) }
extra = yaml_ids - INDEX.keys

puts "Unique concepts in index: #{INDEX.size}"
puts "YAML concept files: #{yaml_ids.size}"
puts ""
puts "=== MISSING FROM DATASET (#{missing.size}) ==="
missing.sort_by { |k| k.split(".").map(&:to_i) }.each do |id|
  puts "  #{id}: #{INDEX[id].join('; ')}"
end

if extra.any?
  puts ""
  puts "=== IN DATASET BUT NOT IN INDEX (#{extra.size}) ==="
  extra.sort_by { |k| k.split(".").map(&:to_i) }.each do |id|
    puts "  #{id}"
  end
end

# Also note: entries 19-20, 42-43, 47-48, 221-222 are preamble references (not concepts)
# Entries 50 is duplicate of 49
# Entries 73, 76 → 7.4.5.2 (échelle non-linéaire = logarithmique + quadratique)
# Entries 192-193 → 6.1.1 (sub-entries of mesure matérialisée)
# Entries 233-234 → 2.4.9 (both presentation)
# Entries 237-238 → 6.4.11 (prototype international/national)
# Entries 277-278 → 4.6.7 (multiple/sous-multiple)
puts ""
puts "Note: 302 index entries map to #{INDEX.size} unique concept numbers (many are synonyms/aliases)"
